### ISSUE TITLE
Create Component: Dialog Component for Login Modal

### ISSUE THREAD

**Issue by akbarbmirza** [akbarbmirza/livestream-sample#1]
#### Description

This component will be used across different pages of the application where users need to authenticate themselves. Currently, we are using a generic dialog component for login, but it lacks some features and customizations that are required specifically for the login process.

#### Tasks

- [ ] Fields for entering username and password
- [ ] "Remember me" checkbox
- [ ] "Forgot your password" link
- [ ] A 'Login' button to submit the details
- [ ] An 'x' icon at the top-right corner to close the dialog

**Comment by akbarbmirza** [comment]
What's the status on this?
